# Generated by Django 5.2 on 2025-04-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='is_vendor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
