# Generated by Django 5.2 on 2025-04-10 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_authuser_is_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='is_vendor',
        ),
    ]
