# Generated by Django 5.2 on 2025-04-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0002_venuemodel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='venuemodel',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='venue/'),
        ),
    ]
