# Generated by Django 5.2 on 2025-04-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0003_city_slug_venuemodel_thumbnail_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
