# Generated by Django 5.2 on 2025-04-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0004_venuemodel_slug_alter_city_name_alter_city_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
