# Generated by Django 5.2 on 2025-04-11 02:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0006_alter_city_slug_alter_price_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
