# Generated by Django 5.2 on 2025-04-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0007_bookingmodel_booked_at_bookingmodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuemodel',
            name='available_date',
        ),
    ]
