# Generated by Django 5.2 on 2025-04-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0008_remove_venuemodel_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='booked_for',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='booked_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
