# Generated by Django 5.2 on 2025-04-27 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0009_bookingmodel_booked_for_alter_bookingmodel_booked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='status',
            field=models.CharField(choices=[('Booked', 'booked'), ('Available', 'available')], default='Available', max_length=25),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='venue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_bookings', to='venue.venuemodel'),
        ),
    ]
