# Generated by Django 5.2 on 2025-04-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0010_venuemodel_status_alter_bookingmodel_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Available', 'Available')], default='Available', max_length=25),
        ),
    ]
