# Generated by Django 5.2 on 2025-04-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0011_bookingmodel_status_alter_venuemodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending')], default='Pending', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='venuemodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Booked', 'Booked'), ('Available', 'Available')], default='Available', max_length=25, null=True),
        ),
    ]
