# Generated by Django 5.2 on 2025-04-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0012_alter_bookingmodel_status_alter_venuemodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuemodel',
            name='status',
        ),
    ]
