# Generated by Django 5.2 on 2025-04-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0013_remove_venuemodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuemodel',
            name='rating',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='status',
            field=models.CharField(blank=True, choices=[('Cancelled', 'Cancelled'), ('Completed', 'Completed'), ('Pending', 'Pending'), ('Paid', 'Paid')], default='Pending', max_length=25, null=True),
        ),
    ]
