# Generated by Django 5.2 on 2025-04-28 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0014_venuemodel_rating_alter_bookingmodel_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venuemodel',
            name='rating',
        ),
        migrations.CreateModel(
            name='VenueRatingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('venue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='venue.venuemodel')),
            ],
        ),
    ]
