# Generated by Django 5.2 on 2025-04-28 12:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venue', '0016_venueratingmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueratingmodel',
            name='rated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 4, 28, 12, 7, 57, 231102, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
